### ISSUE TITLE
How to hide next and prev labels?

### ISSUE THREAD

**Issue by timokleemann** [ddnexus/pagy#233]
Is there a way to hide the `next` and `prev` labels entirely?

I just want arrows in there, so this is what I'm doing right now:

```
en:
  pagy:
    nav:
      prev: "< "
      next: "..."
      gap: " >"
```

```
de:
  pagy:
    nav:
      prev: "< "
      next: "..."
      gap: " >"
```

It feels cumbersome and repetitive, though. 

Any pointers?
