### ISSUE TITLE
Add be: "pagination" entry

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#578]

**Comment by benkoshy** [comment]
@sk8higher 

Thank you again for your contribution to the be locale.

We are in the process to improve the labelling of pagy helpers in order to comply with the [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) standards. 

We are seeking your advice with the pluralized translation of the "page", "pages" label, for each required plural listed below:

```yml
    page_label: 
      one: "?"
      few: "?"
      many: "?"
      other: "?"
```

Please, feel free to post a comment with your translations. You don't need to create a [PR](https://github.com/ddnexus/pagy/blob/d837376dc099724dd8ec50db66563e6ee34e378f/lib/locales/be.yml#L8) (if you don't want to): we can manage it crediting you.

Thank you in advance for your help!
