### ISSUE TITLE
Add ru: "pagination" entry

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#599]

**Comment by MaxB-Net** [comment]
Hello! For RU locale (https://github.com/ddnexus/pagy/blob/master/gem/locales/ru.yml) I suggest:
```
nav:
  one: "Страница"
  few: "Страницы"
  many: "Страниц"
  other: "Страниц"

```
