### ISSUE TITLE
Add tr: "pagination" entry

### ISSUE THREAD

**Issue by ddnexus** [ddnexus/pagy#605]

**Comment by benkoshy** [comment]
I believe we can close this because Turkish uses the "other" translation.

**Comment by ddnexus** [comment]
Dobee have the `tr` translation for "pages"?

**Comment by benkoshy** [comment]
> Dob we have the `tr` translation for "pages"?

We do not have the translation. I made the fatal assumption that "pages" would be the translation. Which means I will re-open a few issues.

**Comment by Cosmo** [comment]
I hope a comment is fine -- if not, please let me know so I can create a PR.

```yml
tr:
  pagy:
    p11n: 'OneOther'
    aria_label:
      nav:
        one: "Sayfa"
        other: "Sayfalar"
      previous: "Önceki"
      next: "Sonraki"
    previous: "&lt;"
    next: "&gt;"
    gap: "&hellip;"
    item_name:
      one: "kayıt"
      other: "kayıtlar"
    info_tag:
      no_count: "Sayfa %{page} / %{pages}"
      no_items: "Hiç %{item_name} bulunamadı"
      single_page: "%{count} %{item_name} gösteriliyor"
      multiple_pages: "%{count} toplamda %{item_name} %{from}-%{to} arası gösteriliyor"
    input_nav_js: "Sayfa %{page_input} / %{pages}"
    limit_tag_js: "Sayfa başına %{limit_input} %{item_name} göster"
```
